name: 'Azure Cosmos DB Emulator'
description: 'Runs the Cosmos DB emulator. Only works on `windows-latest`'
author: 'Jan Piotrowski <piotrowski@gmail.com>'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  parameter_string:
    description: Start-CosmosDbEmulator cmdlet parameters
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    # Apply patch to cmdlet so needed parameters are available
    - run: patch "C:/Program Files/Azure Cosmos DB Emulator/PSModules/Microsoft.Azure.CosmosDB.Emulator/Microsoft.Azure.CosmosDB.Emulator.psm1" < patch/psm1.patch
      shell: bash
    - run: ls -l "C:/Program Files/Azure Cosmos DB Emulator/PSModules/Microsoft.Azure.CosmosDB.Emulator/"
      shell: bash
    - run: ./start-azure-cosmos-db-emulator.ps1
      shell: pwsh
